"use strict";

const VISUAL_INTENTS = Object.freeze({ GENERAL_VISUAL:"GENERAL_VISUAL", PHOTO_REQUEST:"PHOTO_REQUEST", DIAGRAM_REQUEST:"DIAGRAM_REQUEST", ANATOMY:"ANATOMY", HISTORICAL_PERSON:"HISTORICAL_PERSON", COMPARISON:"COMPARISON", CURRENT_EVENT:"CURRENT_EVENT", SCIENTIFIC_OBJECT:"SCIENTIFIC_OBJECT", LOCATION:"LOCATION" });
const VISUAL_TYPES = Object.freeze(["PHOTO","PORTRAIT","DIAGRAM","MAP","ILLUSTRATION","SATELLITE","SCIENTIFIC_IMAGE","LOGO","ICON","UNKNOWN"]);
const STOP = new Set("ve ile bir bu şu nasıl nedir hakkında görsel görseli görseller fotoğraf fotoğrafları image images photo diagram diyagramı yapısı bölümleri bugünkü son gelişmeler".split(" "));
function fold(value){return String(value||"").toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[ı]/g,"i").replace(/[ş]/g,"s").replace(/[ç]/g,"c").replace(/[ğ]/g,"g").replace(/[ö]/g,"o").replace(/[ü]/g,"u").replace(/[^a-z0-9]+/g," ").trim();}
function tokens(value){return [...new Set(fold(value).split(/\s+/).filter(x=>x.length>1&&!STOP.has(x)))];}
function question(analysis){return String(analysis?.originalQuestion||analysis?.question||analysis?.topic||"").trim();}
function comparisonEntities(value){const clean=String(value||"").replace(/\b(?:karşılaştırması|karşılaştırma|farkları|farkı|fark)\b/gi,"").trim();const parts=clean.split(/\s+(?:vs\.?|ile|versus)\s+/i).map(x=>x.trim()).filter(Boolean);return parts.length===2?parts:[];}
function classifyVisualIntent(value,analysis={}) {
  const q=fold(value||question(analysis));
  if(/\b(bugun|bugunku|son|guncel|gelismeler|haber)\b/.test(q))return VISUAL_INTENTS.CURRENT_EVENT;
  if(comparisonEntities(value||question(analysis)).length===2)return VISUAL_INTENTS.COMPARISON;
  if(q.includes("anatomi")||q.includes("kalb")||/\b(kalp|organ|iskelet|damar)\b/.test(q))return VISUAL_INTENTS.ANATOMY;
  if(/\b(fotograf|fotograflari|portre|portrait)\b/.test(q))return /ataturk|einstein|curie|tesla/.test(q)?VISUAL_INTENTS.HISTORICAL_PERSON:VISUAL_INTENTS.PHOTO_REQUEST;
  if(q.includes("diyagram")||/\b(diagram|sema|yapisi|bolumleri)\b/.test(q))return VISUAL_INTENTS.DIAGRAM_REQUEST;
  if(/\b(ataturk|einstein|marie curie)\b/.test(q))return VISUAL_INTENTS.HISTORICAL_PERSON;
  if(/\b(dna|hucre|kara delik|gezegen|mars|gunes sistemi|toryum)\b/.test(q))return VISUAL_INTENTS.SCIENTIFIC_OBJECT;
  if(/\b(ulke|sehir|imparatorluk|roma|harita|location)\b/.test(q))return VISUAL_INTENTS.LOCATION;
  return VISUAL_INTENTS.GENERAL_VISUAL;
}
function resolveEntity(value,analysis={}) {
  const q=fold(value||question(analysis)),topic=String(analysis.topic||value||"").trim();
  if(/\bapple\b/.test(q))return /\b(technology|teknoloji|iphone|mac|company|sirket)\b/.test(q)?"Apple Inc.":/\b(meyve|fruit|food|gida)\b/.test(q)?"apple fruit":topic;
  if(/\bjava\b/.test(q))return (q.includes("program")||/\b(yazilim|software|language|kod)\b/.test(q))?"Java programming language":/\b(ada|island|endonezya|indonesia)\b/.test(q)?"Java island Indonesia":topic;
  if(/\bmercury\b/.test(q))return /\b(planet|gezegen|space|uzay)\b/.test(q)?"Mercury planet":/\b(element|metal|kimya|chemical)\b/.test(q)?"Mercury chemical element":topic;
  if(/\btesla\b/.test(q))return /\b(araba|car|vehicle|company|sirket)\b/.test(q)?"Tesla Inc electric vehicle":/\b(nikola|scientist|bilim)\b/.test(q)?"Nikola Tesla portrait":topic;
  return topic||String(value||"").trim();
}
function expandImageQueries(value,analysis={}){const raw=value||question(analysis),intent=classifyVisualIntent(raw,analysis),entity=resolveEntity(raw,analysis),comparison=comparisonEntities(raw);if(intent===VISUAL_INTENTS.CURRENT_EVENT||/^(java|apple|mercury|tesla)$/.test(fold(raw)))return[];if(comparison.length)return comparison.slice(0,2).map((item,index)=>({query:resolveEntity(item,{topic:item}),side:index===0?"left":"right"}));const q=[];const add=x=>{if(x&&!q.some(y=>fold(y.query)===fold(x)))q.push({query:x,side:null});};add(entity);if(intent===VISUAL_INTENTS.HISTORICAL_PERSON){add(`${entity} portrait`);add(`${entity} photograph`);}else if(intent===VISUAL_INTENTS.ANATOMY){add(`${entity} anatomy diagram`);add(`${entity} medical illustration`);}else if(intent===VISUAL_INTENTS.DIAGRAM_REQUEST){add(`${entity} diagram`);add(`${entity} scientific illustration`);}else if(/\bmars\b/.test(fold(entity))){add("Mars planet");add("Mars surface NASA");}else if(/\bkara delik\b/.test(fold(entity))){add("black hole");add("accretion disk");add("stellar collapse diagram");}else if(/\bdna\b/.test(fold(entity))){add("DNA double helix");add("DNA structure diagram");}else if(intent===VISUAL_INTENTS.LOCATION){add(`${entity} map`);add(`${entity} photograph`);}return q.slice(0,4);}
function classifyImageType(item={}){const text=fold(`${item.title||""} ${item.description||""} ${item.mime||""}`);if(/\b(logo|wordmark|emblem|coat of arms|badge)\b/.test(text))return"LOGO";if(/\b(icon|symbol|pictogram)\b/.test(text))return"ICON";if(/\b(portrait|portre|headshot)\b/.test(text))return"PORTRAIT";if(/\b(diagram|schematic|anatomy|structure|chart)\b/.test(text))return"DIAGRAM";if(/\b(map|harita|atlas)\b/.test(text))return"MAP";if(/\b(satellite|orbiter|landsat)\b/.test(text))return"SATELLITE";if(/\b(illustration|drawing|engraving|painting)\b/.test(text))return"ILLUSTRATION";if(/\b(microscope|telescope|nasa|esa|scientific)\b/.test(text))return"SCIENTIFIC_IMAGE";if(/\b(photo|photograph|jpg|jpeg)\b/.test(text))return"PHOTO";return"UNKNOWN";}
function canonical(value){try{const url=new URL(value);url.search="";return decodeURIComponent(url.pathname).replace(/\/thumb\/(.+?)\/\d+px-[^/]+$/i,"/$1").replace(/\b\d+px-/i,"").toLowerCase();}catch{return"";}}
function safeHttps(value){try{const url=new URL(value);return url.protocol==="https:"&&(["upload.wikimedia.org","commons.wikimedia.org"].includes(url.hostname)||url.hostname.endsWith(".nasa.gov")||url.hostname.endsWith(".esa.int")||url.hostname.endsWith(".usgs.gov"));}catch{return false;}}
function expectedTypes(intent){if(intent===VISUAL_INTENTS.HISTORICAL_PERSON)return["PORTRAIT","PHOTO"];if([VISUAL_INTENTS.ANATOMY,VISUAL_INTENTS.DIAGRAM_REQUEST].includes(intent))return["DIAGRAM","SCIENTIFIC_IMAGE","ILLUSTRATION"];if(intent===VISUAL_INTENTS.LOCATION)return["MAP","SATELLITE","PHOTO"];if(intent===VISUAL_INTENTS.PHOTO_REQUEST)return["PHOTO","PORTRAIT","SCIENTIFIC_IMAGE"];return["SCIENTIFIC_IMAGE","PHOTO","DIAGRAM","ILLUSTRATION","PORTRAIT","SATELLITE","MAP","UNKNOWN"];}
function scoreCandidate(item,context){const queryTokens=tokens(context.entity),textTokens=tokens(`${item.title} ${item.description}`),overlap=queryTokens.filter(x=>textTokens.includes(x)).length/Math.max(1,queryTokens.length);const type=item.visualType||classifyImageType(item);let score=Math.round(overlap*60);if(fold(item.title).includes(fold(context.entity)))score+=25;if(expectedTypes(context.intent).includes(type))score+=14;if(type==="LOGO"||type==="ICON")score-=70;if(/\b(logo|icon|flag|coat of arms|badge|symbol|placeholder)\b/.test(fold(`${item.title} ${item.description}`))&&!context.allowGraphic)score-=55;if(Number(item.width)>=500||Number(item.height)>=500)score+=8;else if(item.width&&item.height)score-=18;if(/nasa|esa|usgs/.test(fold(`${item.attribution} ${item.description} ${item.sourceName}`)))score+=7;if(item.mime==="image/svg+xml")score-=80;return Math.max(0,Math.min(100,score));}
function createContext(value,analysis={}){const raw=value||question(analysis),intent=classifyVisualIntent(raw,analysis),entity=resolveEntity(raw,analysis);return{query:raw,entity,intent,queries:expandImageQueries(raw,analysis),allowGraphic:/\b(logo|flag|bayrak|icon|symbol)\b/.test(fold(raw)),comparisonEntities:comparisonEntities(raw)};}
function rankCandidates(candidates,context){const seen=new Set(),titleSeen=new Set(),pageSeen=new Set();return(candidates||[]).map((raw,index)=>{const item={...raw};item.visualType=classifyImageType(item);item.relevanceScore=scoreCandidate(item,context);item.id=item.id||`visual-${index+1}`;item.license=item.license||"Belirtilmemiş";item.attribution=item.attribution||item.sourceName||item.source||"Wikimedia Commons";item.sourceRefs=[...new Set([...(item.sourceRefs||[]),item.sourceUrl||item.url].filter(Boolean))];item.isHero=false;return item;}).filter(item=>safeHttps(item.url||item.image)&&safeHttps(item.thumbnailUrl||item.image||item.url)&&item.relevanceScore>=28&&(!["LOGO","ICON"].includes(item.visualType)||context.allowGraphic)).filter(item=>{const key=canonical(item.original||item.url||item.image),title=fold(String(item.title||"").replace(/\b\d+px-/i,"")),page=canonical(item.sourceUrl);if(!key||seen.has(key)||(title&&titleSeen.has(title))||(page&&pageSeen.has(page)))return false;seen.add(key);if(title)titleSeen.add(title);if(page)pageSeen.add(page);return true;}).sort((a,b)=>b.relevanceScore-a.relevanceScore||Number(b.width||0)*Number(b.height||0)-Number(a.width||0)*Number(a.height||0)).slice(0,8).map((item,index)=>({...item,isHero:index===0}));}

module.exports={VISUAL_INTENTS,VISUAL_TYPES,fold,tokens,comparisonEntities,classifyVisualIntent,resolveEntity,expandImageQueries,classifyImageType,canonical,safeHttps,scoreCandidate,createContext,rankCandidates};
