"use strict";
const assert = require("node:assert/strict"); const signatures = require("../brain/claimSignatures"); const families = require("../brain/eventFamilies"); const quality = require("../brain/currentContentQuality");
const providers = require("../brain/currentProviders"); const intelligence = require("../brain/researchIntelligence"); const freshness = require("../brain/freshness");
const claim = (id, text, number, source) => ({ id, eventId: `event-${id}`, text, numericValue: number, sourceRefs: [source], sourceCount: 1, independentDomains: 1, authority: 100, confidence: "Orta", signature: signatures.signature(text, { publishedAt: "2026-08-12T10:00:00Z" }) });
const numeric = [claim("a", "CISA added 3 vulnerabilities to the KEV catalog.", 3, "https://a.gov/x"), claim("b", "CISA added 5 vulnerabilities to the KEV catalog.", 5, "https://b.gov/x")]; const numericFamilies = families.buildFamilies([], numeric); assert.equal(numericFamilies.length, 1); assert.equal(numericFamilies[0].claims.length, 2); assert.equal(numericFamilies[0].contradictions[0].type, "NUMERIC_CONFLICT"); assert.equal(numericFamilies[0].contradictions[0].severity, "HIGH"); assert.equal(quality.buildCurrentQuiz([], numeric), null);
const dates = [claim("c", "NASA Artemis mission will launch on 12 Aug.", null, "https://a.gov/d"), claim("d", "NASA Artemis mission will launch on 13 Aug.", null, "https://b.gov/d")]; const dateFamily = families.buildFamilies([], dates); assert.equal(dateFamily.length, 1); assert.equal(dateFamily[0].contradictions[0].type, "DATE_CONFLICT"); assert.equal(dateFamily[0].contradictions[0].severity, "MEDIUM");
const statuses = [claim("e", "NASA Artemis mission completed.", null, "https://a.gov/s"), claim("f", "NASA Artemis mission delayed.", null, "https://b.gov/s")]; const statusFamily = families.buildFamilies([], statuses); assert.equal(statusFamily.length, 1); assert.equal(statusFamily[0].contradictions[0].type, "STATUS_CONFLICT"); assert.equal(statusFamily[0].contradictions[0].severity, "HIGH");
const query = "Bugünkü siber güvenlik gelişmeleri"; const item = (domain, summary, url) => ({ providerId: domain, sourceName: domain, source: domain, domain, title: "CISA KEV Catalog Update", summary, text: summary, url, publishedAt: "2026-08-12T10:00:00Z", authority: 100, trust: "official", currentRelevanceVerified: true, subcategory: "CYBERSECURITY" }); const items = [item("a.gov", "CISA added 3 vulnerabilities to the KEV catalog.", "https://a.gov/x"), item("b.gov", "CISA added 5 vulnerabilities to the KEV catalog.", "https://b.gov/x")]; const events = providers.clusterEvents(items); const detection = freshness.detectFreshness(query, new Date("2026-08-12T12:00:00Z")); const context = intelligence.buildContext(query, detection); const dto = intelligence.enhanceResult(intelligence.createCurrentResult(query, { items, events, checkedAt: "2026-08-12T12:00:00Z" }, detection, context), context); assert.equal(dto.structuredContent.sections.length, 1); assert.equal(dto.structuredContent.sections[0].claims.length, 2); assert.equal(dto.structuredContent.sections[0].sources.length, 2); assert.equal(dto.structuredContent.sections[0].contradictions[0].type, "NUMERIC_CONFLICT"); assert.match(dto.summary, /kaynaklar farklı bilgiler veriyor/i); assert.match(dto.ai.lesson.detailed, /Kaynaklar bu ayrıntıda farklı bilgi veriyor/i); assert.equal(dto.brain.quiz, null); assert.equal(dto.brain.flashcards.length, 0);
console.log("PASS  event families, neutral numeric/date/status contradictions, severity, variant provenance, and quiz contradiction safety");
