"use strict";
const assert = require("node:assert/strict");
const metrics = require("../brain/metrics");
metrics.reset();
metrics.requestStarted("/api/research");
metrics.requestCompleted("/api/research", 200, 12);
metrics.requestCompleted("/api/research", 500, 20);
metrics.recordProvider("nasa-breaking", 4, true, 2, false);
metrics.recordStorage("learning-memory", "write", 3, true);
metrics.recordCurrentCoverage(4, 3, 2);
metrics.state.cache.hit += 1;
const summary = metrics.summary();
assert.equal(summary.requests.total, 1);
assert.equal(summary.requests.errors, 1);
assert.equal(summary.routes._api_research.count, 1);
assert.equal(summary.routes._api_research.errors, 1);
assert.equal(summary.providers["nasa-breaking"].itemCount, 2);
assert.equal(summary.storage["learning-memory"].writes, 1);
assert.equal(summary.research.currentItems, 4);
assert.equal(summary.research.eventClusters, 3);
assert.equal(summary.research.independentDomains, 2);
assert.equal(JSON.stringify(summary).includes("Mars"), false);
metrics.reset();
assert.equal(metrics.summary().requests.total, 0);
console.log("PASS  metrics aggregation, reset, provider counters, error counters, and privacy");
