"use strict";
const assert = require("node:assert/strict");
const metrics = require("../brain/metrics");
metrics.reset();
metrics.requestStarted("/api/research");
metrics.requestCompleted("/api/research", 200, 12);
metrics.requestCompleted("/api/research", 500, 20);
metrics.recordProvider("nasa-breaking", 4, true, 2, false);
metrics.recordStorage("learning-memory", "write", 3, true);
metrics.recordCurrentCoverage(4, 3, 2);
metrics.recordClaims([{ independentDomains: 2 }, { independentDomains: 1 }], [{ claimKey: "x" }], { verified: true });
metrics.recordClaimMatching({ eventCrossSource: 1, bilingualMatches: 1, signatureMatches: 2, rejected: 3, sameOrgMultiSource: 1 });
metrics.state.cache.hit += 1;
const summary = metrics.summary();
assert.equal(summary.requests.total, 1);
assert.equal(summary.requests.errors, 1);
assert.equal(summary.routes._api_research.count, 1);
assert.equal(summary.routes._api_research.errors, 1);
assert.equal(summary.providers["nasa-breaking"].itemCount, 2);
assert.equal(summary.storage["learning-memory"].writes, 1);
assert.equal(summary.research.currentItems, 4);
assert.equal(summary.research.eventClusters, 3);
assert.equal(summary.research.independentDomains, 2);
assert.equal(summary.claims.count, 2);
assert.equal(summary.claims.crossSource, 1);
assert.equal(summary.claims.contradictions, 1);
assert.equal(summary.claims.quizVerifiedQuestions, 1);
assert.equal(summary.claims.eventCrossSource, 1); assert.equal(summary.claims.bilingualMatches, 1); assert.equal(summary.claims.signatureMatches, 2); assert.equal(summary.claims.matchRejected, 3); assert.equal(summary.claims.sameOrgMultiSource, 1);
assert.equal(JSON.stringify(summary).includes("Mars"), false);
metrics.reset();
assert.equal(metrics.summary().requests.total, 0);
console.log("PASS  metrics aggregation, reset, provider counters, error counters, and privacy");
