"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),organization=require("../auth/noteOrganization"),memory=require("../repositories/memoryRepository"),presets=require("../repositories/noteFilterPresetsRepository");
assert.deepEqual(organization.list({}),{workspaceArea:"",contentType:"",archiveState:"active",sort:"updated",search:"",limit:20,offset:0});
assert.equal(organization.list({area:"work",type:"meeting",archive:"all",sort:"title",limit:"50",offset:"20",q:"atlas"}).limit,50);
for(const bad of [{sort:"random"},{archive:"trash"},{limit:"51"},{limit:"x"},{offset:"-1"},{q:"x".repeat(81)}])assert.throws(()=>organization.list(bad),/INVALID_NOTE_ORGANIZATION/);
assert.deepEqual(organization.patch({isPinned:true,isArchived:false}),{isPinned:true,isArchived:false});assert.throws(()=>organization.patch({isPinned:"yes"}),/INVALID_NOTE_ORGANIZATION/);assert.throws(()=>organization.patch({isPinned:true,ownerUserId:"x"}),/INVALID_NOTE_ORGANIZATION/);
assert.equal(organization.preset({name:" İş Notlarım ",workspaceArea:"work",contentType:"note",archiveState:"active",sort:"updated"}).name,"İş Notlarım");for(const bad of [{name:""},{name:"x".repeat(41)},{name:"<script>",userId:"x"},{name:"x",sort:"bad"}])assert.throws(()=>organization.preset(bad),/INVALID_NOTE_ORGANIZATION/);
const mapped=memory.mapMemory({id:"1",topic:"x",title:"x"});assert.equal(mapped.isPinned,false);assert.equal(mapped.isArchived,false);
const calls=[],client={query:async(text,values)=>{calls.push({text,values});return{rows:[{exists:true,record:{id:"1",topic:"x",title:"x",is_pinned:true,is_archived:false}}]};}};(async()=>{const changed=await memory.organizeOwned("1",{kind:"user",id:"owner"},{isPinned:true},client);assert.equal(changed.memory.isPinned,true);assert.match(calls[0].text,/owner_user_id=\$2/);assert.match(fs.readFileSync("db/migrations/013_note_organization.sql","utf8"),/user_note_filter_presets/);assert.equal(presets.map({id:"1",name:"x",archive_state:"active",sort_order:"updated"}).archiveState,"active");console.log("PASS  note organization validation, legacy defaults, ownership SQL, preset bounds and migration");})().catch(e=>{console.error(e);process.exitCode=1;});
