"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),{spawn}=require("node:child_process"),{Pool}=require("pg");
if(!process.env.TEST_DATABASE_URL){console.log("SKIP  notebook background PostgreSQL E2E: TEST_DATABASE_URL is not set");process.exit(0);}
if(process.env.DATABASE_URL&&process.env.DATABASE_URL!==process.env.TEST_DATABASE_URL)throw new Error("TEST_DATABASE_URL_ONLY");
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL}),suffix=crypto.randomBytes(5).toString("hex"),names=[`bg_a_${suffix}`,`bg_b_${suffix}`,`bg_s_${suffix}`,`bg_t_${suffix}`],password="Notebook-bg-test!",png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+3MxZ5wAAAABJRU5ErkJggg==","base64");let child;
async function wait(base){for(let i=0;i<80;i++){try{if((await fetch(base+"/api/status")).ok)return;}catch(_){}await new Promise(r=>setTimeout(r,100));}throw new Error("SERVER_TIMEOUT");}
async function stop(){if(child&&child.exitCode===null){child.kill("SIGTERM");await new Promise(r=>child.once("exit",r));}}
async function json(base,path,method="GET",body,cookie){const response=await fetch(base+path,{method,headers:{Accept:"application/json",Origin:base,...(body?{"Content-Type":"application/json"}:{}),...(cookie?{Cookie:cookie}:{})},body:body&&JSON.stringify(body)});return{response,body:await response.json().catch(()=>({}))};}
async function image(base,method,cookie,data=png,headers={}){return fetch(base+"/api/auth/notebook-background",{method,headers:{Origin:base,"Content-Type":"image/png",Cookie:cookie,...headers},body:method==="PUT"?data:undefined});}
(async()=>{const port=41000+crypto.randomInt(5000),base=`http://127.0.0.1:${port}`;const start=()=>spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),AUTH_MODE:"production",ACCESS_MODE:"authenticated",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","ignore","ignore"]});child=start();await wait(base);
const regs=[];for(const username of names)regs.push(await json(base,"/api/auth/register","POST",{username,password}));const cookies=regs.map(x=>String(x.response.headers.get("set-cookie")).split(";")[0]);await pool.query("UPDATE users SET role='STUDENT' WHERE username=$1",[names[2]]);await pool.query("UPDATE users SET role='TEACHER' WHERE username=$1",[names[3]]);
assert.equal((await image(base,"PUT","",png)).status,401);assert.equal((await image(base,"PUT",cookies[0],png,{"X-Notebook-Position":"top","X-Notebook-Overlay":"44","X-Notebook-Blur":"6","X-User-Id":regs[1].body.user.id})).status,200);
let get=await image(base,"GET",cookies[0]);assert.equal(get.status,200);assert.equal(get.headers.get("content-type"),"image/png");assert.equal(get.headers.get("x-content-type-options"),"nosniff");assert.equal(get.headers.get("cache-control"),"private, no-store");assert.equal(get.headers.get("x-notebook-position"),"top");assert.deepEqual(Buffer.from(await get.arrayBuffer()),png);
assert.equal((await image(base,"GET",cookies[1])).status,204,"other user cannot fetch A");assert.equal((await image(base,"DELETE",cookies[1])).status,200,"other user delete is scoped to self");assert.equal((await image(base,"GET",cookies[0])).status,200,"A survives B delete");
for(const i of [1,2,3])assert.equal((await image(base,"PUT",cookies[i],png,{"X-Notebook-Position":"bottom","X-Notebook-Overlay":"30","X-Notebook-Blur":"2"})).status,200);
assert.equal((await fetch(base+"/api/auth/notebook-background",{method:"PUT",headers:{Origin:base,"Content-Type":"image/svg+xml",Cookie:cookies[0]},body:"<svg/>"})).status,400);assert.equal((await image(base,"PUT",cookies[0],Buffer.from("<html>"))).status,400);assert.equal((await image(base,"PUT",cookies[0],Buffer.alloc(900*1024+1))).status,413);
await stop();child=start();await wait(base);assert.equal((await image(base,"GET",cookies[0])).status,200,"restart persistence");assert.equal((await image(base,"DELETE",cookies[0])).status,200);assert.equal((await image(base,"GET",cookies[0])).status,204);
const rows=await pool.query("SELECT u.username,b.byte_size,b.position FROM notebook_backgrounds b JOIN users u ON u.id=b.user_id WHERE u.username=ANY($1::text[])",[names]);assert.equal(rows.rowCount,3);assert.ok(rows.rows.every(r=>r.byte_size===png.length));console.log("PASS  notebook background PostgreSQL persistence, private owner isolation, USER/STUDENT/TEACHER, validation, bounded replace and restart/remove");
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await stop();await pool.query("DELETE FROM users WHERE username=ANY($1::text[])",[names]).catch(()=>{});await pool.end();});
