
"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),{spawn}=require("node:child_process"),{chromium}=require("playwright-core"),{Pool}=require("pg"),{bindRoute}=require("./helpers/workspaceShellNavigation");
if(!process.env.TEST_DATABASE_URL){console.log("SKIP  Defterim workspace Edge: TEST_DATABASE_URL is not set");process.exit(0);}if(process.env.DATABASE_URL&&process.env.DATABASE_URL!==process.env.TEST_DATABASE_URL)throw Error("TEST_DATABASE_URL_ONLY");
const EDGE="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",username=`notebook_ui_${crypto.randomBytes(5).toString("hex")}`,password="Notebook-workspace-15.6!",pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,max:1});let child,browser;
async function ready(base){for(let i=0;i<140;i++){try{if((await fetch(base+"/api/status")).ok)return;}catch(_){}await new Promise(r=>setTimeout(r,100));}throw Error("SERVER_TIMEOUT");}
(async()=>{const port=44000+crypto.randomInt(900),base=`http://127.0.0.1:${port}`;child=spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),ACCESS_MODE:"authenticated",AUTH_MODE:"production",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","ignore","ignore"]});await ready(base);browser=await chromium.launch({executablePath:EDGE,headless:true});const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[],failed=[];page.on("pageerror",e=>errors.push(e.message));page.on("response",r=>{if(r.status()>=500)failed.push(`${r.status()} ${r.url()}`)});await page.goto(base);await page.locator("[data-open-register]").click();await page.getByLabel("Kullanıcı adı",{exact:true}).fill(username);await page.getByLabel("Parola",{exact:true}).fill(password);await page.getByLabel("Parola tekrar").fill(password);await page.getByRole("button",{name:"Hesap oluştur"}).click();await page.locator(".workspace-dialog[open]").waitFor();await page.getByRole("button",{name:"Şimdilik geç"}).click();await page.locator(".workspace-dialog").waitFor({state:"hidden"});await bindRoute(page,"notebook");await page.locator("#notebookWorkspace156").waitFor();
await page.evaluate(async()=>{for(let i=0;i<22;i++){let response=await fetch("/api/memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:"Workspace Note "+String(i).padStart(2,"0"),content:"Premium workspace content "+i,workspaceArea:i%2?"work":"creative",contentType:i%3?"note":"idea",tags:["phase3"],metadata:{}})});if(!response.ok)throw Error("FIXTURE_CREATE");}await window.YDSmartNotes.load(false);});await page.getByText("Workspace Note 19",{exact:true}).waitFor();assert.equal(await page.locator("#notebookList .smart-note-card").count(),20);assert.equal(await page.locator("[data-notebook-area]").count(),7);
const workResponse=page.waitForResponse(r=>r.url().includes("/api/memory/list")&&r.status()===200);await page.locator('[data-notebook-area="work"]').click();await workResponse;assert.equal(await page.locator('[data-notebook-area="work"]').getAttribute("aria-pressed"),"true");const typeResponse=page.waitForResponse(r=>r.url().includes("/api/memory/list")&&r.status()===200);await page.locator("#smartNoteType").selectOption("idea");await typeResponse;await page.locator("#smartNoteType").selectOption("");await page.locator('[data-notebook-area=""]').click();await page.locator("#smartNoteSearch").fill("Workspace Note 19");await page.waitForTimeout(350);await page.getByText("Workspace Note 19",{exact:true}).waitFor();
const open=page.getByRole("button",{name:"Workspace Note 19 kaydını aç"});await open.click();await page.locator(".yd-notebook-detail:not([hidden]) h2").waitFor();assert.match(await page.locator(".yd-notebook-full-copy").textContent(),/Premium workspace content/);await page.keyboard.press("Escape");assert.equal(await open.evaluate(n=>n===document.activeElement),true);
await page.locator("#smartNoteSearch").fill("");await page.waitForTimeout(350);const first=page.locator(".smart-note-card").first();await first.locator("summary").click();await first.getByRole("button",{name:"Notu sabitle"}).click();await page.getByText("Sabitlendi",{exact:true}).first().waitFor();await page.locator(".smart-note-card").first().locator("summary").click();await page.locator(".smart-note-card").first().getByRole("button",{name:"Notu arşivle"}).click();await page.getByText("Not arşivlendi.").waitFor();await page.locator("#smartNoteArchive").selectOption("archived");await page.locator(".smart-note-card").first().waitFor();await page.locator(".smart-note-card").first().locator("summary").click();await page.locator(".smart-note-card").first().getByRole("button",{name:"Arşivden çıkar"}).click();
await page.locator("#smartNoteArchive").selectOption("active");await page.locator("#smartNoteMore").click();await page.waitForFunction(()=>document.querySelectorAll("#notebookList .smart-note-card").length>20);for(const width of [360,390,768,1024,1366]){await page.setViewportSize({width,height:width<700?844:768});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=0,"overflow "+width);}await page.setViewportSize({width:1366,height:768});const ratio=await page.evaluate(()=>document.documentElement.scrollHeight/innerHeight);assert.ok(ratio<=1.15,`BODY_RATIO_${ratio}`);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(`PASS  real Edge Defterim USER area/type/search/detail/pin/archive/restore/pagination, responsive matrix and body ratio=${ratio.toFixed(3)}`);
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(child&&child.exitCode===null){child.kill("SIGTERM");await new Promise(r=>child.once("exit",r));}await pool.query("DELETE FROM users WHERE username=$1",[username]).catch(()=>{});await pool.end();});
