"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),{spawn}=require("node:child_process"),{Pool}=require("pg"),{chromium}=require("playwright-core");
if(!process.env.TEST_DATABASE_URL){console.log("SKIP  notebook background Edge E2E: TEST_DATABASE_URL is not set");process.exit(0);}const EDGE="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";if(!fs.existsSync(EDGE)){console.log("SKIP  notebook background Edge E2E: Edge is not installed");process.exit(0);}
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL}),suffix=crypto.randomBytes(5).toString("hex"),names=[`bg_edge_u_${suffix}`,`bg_edge_s_${suffix}`,`bg_edge_t_${suffix}`],password="Notebook-edge-test!",file={name:"notebook.png",mimeType:"image/png",buffer:fs.readFileSync("assets/images/yasayan-defter-official-logo.png")};let child,browser;
async function wait(base){for(let i=0;i<80;i++){try{if((await fetch(base+"/api/status")).ok)return;}catch(_){}await new Promise(r=>setTimeout(r,100));}throw new Error("SERVER_TIMEOUT");}
async function register(page,name){await page.getByRole("button",{name:/Hesap oluştur/}).click();await page.getByLabel("Kullanıcı adı",{exact:true}).fill(name);await page.getByLabel("Parola",{exact:true}).fill(password);await page.getByLabel("Parola tekrar").fill(password);await page.getByRole("button",{name:"Hesap oluştur"}).click();await page.getByRole("button",{name:/Çıkış yap/}).waitFor();await page.locator(".workspace-dialog[open]").waitFor();await page.getByRole("button",{name:"Şimdilik geç"}).click();await page.locator(".workspace-dialog").waitFor({state:"hidden"});}
async function upload(page){await page.locator("#notebookBackgroundFile").setInputFiles(file);await page.getByText(/Önizleme hazır/).waitFor();await page.locator("#notebookBackgroundOverlay").fill("48");await page.locator("#notebookBackgroundBlur").fill("5");await page.locator("#notebookBackgroundPosition").selectOption("top");await page.locator("#applyNotebookBackground").click();await page.getByText("Defter arka planınız uygulandı.").waitFor();assert.equal(await page.locator("html").getAttribute("data-notebook-background"),"custom");}
(async()=>{const port=46000+crypto.randomInt(1500),base=`http://localhost:${port}`;child=spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),AUTH_MODE:"production",ACCESS_MODE:"authenticated",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","ignore","ignore"]});await wait(base);browser=await chromium.launch({executablePath:EDGE,headless:true});const context=await browser.newContext({viewport:{width:390,height:850}}),page=await context.newPage(),consoleErrors=[],pageErrors=[],unexpected=[];page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text())});page.on("pageerror",e=>pageErrors.push(e.message));page.on("response",r=>{if([401,403,500].includes(r.status()))unexpected.push(`${r.status()} ${r.url()}`)});
await page.goto(base);await page.locator("#personalizationPanel").waitFor();await upload(page);await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.notebookBackground==="custom");await page.locator("#removeNotebookBackground").click();await page.getByText("Özel arka plan kaldırıldı.").waitFor();await page.reload();assert.equal(await page.locator("html").getAttribute("data-notebook-background"),null,"public IndexedDB clear");
await register(page,names[0]);await upload(page);for(const theme of ["living","light","night","focus"]){await page.locator(`label[for="pref-theme-${theme}"]`).click();assert.equal(await page.locator("html").getAttribute("data-notebook-background"),"custom");}await page.locator('label[for="pref-notebookWritingStyle-handwriting"]').click();await page.locator('label[for="pref-notebookPageStyle-lined"]').click();assert.equal(await page.locator("#notebookSection").count(),1);assert.notEqual(await page.locator("#notebookSection").evaluate(node=>getComputedStyle(node,"::before").backgroundImage),"none");await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.notebookBackground==="custom");await page.getByRole("button",{name:/Çıkış yap/}).click();await page.locator("[data-open-login]").click();await page.getByLabel("Kullanıcı adı veya e-posta").fill(names[0]);await page.getByLabel("Parola",{exact:true}).fill(password);await page.getByRole("button",{name:"Giriş yap"}).click();await page.waitForFunction(()=>document.documentElement.dataset.notebookBackground==="custom");
await page.locator("#removeNotebookBackground").click();await page.getByText("Özel arka plan kaldırıldı.").waitFor();for(const width of [360,390,768,1024,1366]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),0,`overflow ${width}`);}assert.equal(await page.locator("#notebookBackgroundStatus").getAttribute("aria-live"),"polite");
for(let i=1;i<3;i++){await page.getByRole("button",{name:/Çıkış yap/}).click();await register(page,names[i]);await pool.query("UPDATE users SET role=$1 WHERE username=$2",[i===1?"STUDENT":"TEACHER",names[i]]);await upload(page);}
assert.deepEqual(consoleErrors,[]);assert.deepEqual(pageErrors,[]);assert.deepEqual(unexpected,[]);console.log("PASS  real Edge public/USER/STUDENT/TEACHER photo picker, preview, theme/style/page compatibility, persistence, removal, accessibility and responsive matrix");
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(child&&child.exitCode===null)child.kill("SIGTERM");await pool.query("DELETE FROM users WHERE username=ANY($1::text[])",[names]).catch(()=>{});await pool.end();});
