"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { createJsonStore } = require("../brain/storage/jsonStore");

const dir = fs.mkdtempSync(path.join(os.tmpdir(), "yasayan-storage-"));
const file = path.join(dir, "records.json");
const store = createJsonStore(file, { expected: "array", fallback: [] });
assert.deepEqual(store.read().value, []);
assert.equal(store.write([{ id: 1 }]).ok, true);
assert.equal(store.write([{ id: 2 }]).ok, true);
assert.deepEqual(store.read().value, [{ id: 2 }]);
fs.writeFileSync(`${file}.bak`, JSON.stringify([{ id: "backup" }]));
fs.writeFileSync(file, "{broken");
assert.deepEqual(store.read().value, [{ id: "backup" }]);
fs.writeFileSync(`${file}.bak`, "{broken");
fs.writeFileSync(file, "{broken");
assert.deepEqual(store.read().value, []);
const versioned = createJsonStore(path.join(dir, "versioned.json"), { expected: "array", fallback: [] });
fs.writeFileSync(versioned.file, JSON.stringify({ version: 1, data: [{ id: "legacy" }] }));
assert.deepEqual(versioned.read().value, [{ id: "legacy" }]);
fs.writeFileSync(versioned.file, JSON.stringify({ version: 99, data: [{ id: "future" }] }));
assert.deepEqual(versioned.read().value, []);

process.env.YASAYAN_QUIZ_ATTEMPTS_FILE = path.join(dir, "quiz-attempts.json");
const sessions = require("../brain/quizSessions");
const research = { query: "Mars", structuredContent: { keyFacts: [{ text: "Mars kayalık bir gezegendir.", concept: "Gezegen" }, { text: "Mars'ın iki uydusu vardır.", concept: "Uydular" }, { text: "Mars atmosferi incedir.", concept: "Atmosfer" }] } };
const started = sessions.start({ research, count: 5, difficulty: "medium", type: "multiple-choice" }, "", "student-a");
assert.ok(started.quiz.attemptId);
const question = started.session.quiz.questions[0];
const correct = question.correctAnswer;
assert.equal(sessions.answer(started.quiz.attemptId, question.id, correct, false, "student-a").result.correct, true);
sessions.reloadForTests();
assert.ok(sessions.get(started.quiz.attemptId));
assert.equal(sessions.answer(started.quiz.attemptId, question.id, correct, false, "student-a").error, "DUPLICATE_ANSWER");
assert.equal(sessions.complete(started.quiz.attemptId, "student-b").error, "STUDENT_MISMATCH");
const complete = sessions.complete(started.quiz.attemptId, "student-a");
assert.equal(complete.duplicate, false);
sessions.reloadForTests();
const duplicate = sessions.complete(started.quiz.attemptId, "student-a");
assert.equal(duplicate.duplicate, true);
assert.equal(duplicate.summary.xpAwarded, complete.summary.xpAwarded);
sessions.resetForTests();
fs.rmSync(dir, { recursive: true, force: true });
console.log("PASS  JSON store recovery, migration, quiz restart persistence, immutability, and isolation");
