"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),{spawn}=require("node:child_process"),{Pool}=require("pg"),{chromium}=require("playwright-core");
if(!process.env.TEST_DATABASE_URL){console.log("SKIP  personalization Edge E2E: TEST_DATABASE_URL is not set");process.exit(0);} const EDGE="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";if(!fs.existsSync(EDGE)){console.log("SKIP  personalization Edge E2E: Edge is not installed");process.exit(0);}
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL}),name=`pref_edge_${crypto.randomBytes(5).toString("hex")}`,password="Personalization-edge!";let child,browser;
async function wait(base){for(let i=0;i<70;i++){try{if((await fetch(base+"/api/status")).ok)return;}catch(_){}await new Promise(r=>setTimeout(r,100));}throw new Error("SERVER_TIMEOUT");}
(async()=>{const port=39000+crypto.randomInt(7000),base=`http://localhost:${port}`;child=spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),AUTH_MODE:"production",ACCESS_MODE:"authenticated",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","ignore","ignore"]});await wait(base);browser=await chromium.launch({executablePath:EDGE,headless:true});const page=await browser.newPage({viewport:{width:390,height:850}}),consoleErrors=[],pageErrors=[],unexpected=[];page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text())});page.on("pageerror",e=>pageErrors.push(e.message));page.on("response",r=>{if([401,403,500].includes(r.status()))unexpected.push(`${r.status()} ${r.url()}`)});
await page.goto(base);await page.locator("#personalizationPanel").waitFor();await page.locator('label[for="pref-theme-night"]').click();await page.locator('label[for="pref-notebookWritingStyle-handwriting"]').click();await page.locator('label[for="pref-notebookPageStyle-dotted"]').click();await page.getByRole("button",{name:"Tercihleri kaydet"}).click();await page.reload();assert.equal(await page.locator("html").getAttribute("data-resolved-theme"),"night");
await page.getByRole("button",{name:/Hesap oluştur/}).click();await page.getByLabel("Kullanıcı adı",{exact:true}).fill(name);await page.getByLabel("Parola",{exact:true}).fill(password);await page.getByLabel("Parola tekrar").fill(password);await page.getByRole("button",{name:"Hesap oluştur"}).click();await page.getByRole("button",{name:/Çıkış yap/}).waitFor();await page.locator(".workspace-dialog[open]").waitFor();await page.getByRole("button",{name:"Şimdilik geç"}).click();await page.locator(".workspace-dialog").waitFor({state:"hidden"});await page.locator('.yd-shell-nav-item[data-shell-page="profile"]').click();await page.waitForFunction(()=>document.documentElement.dataset.resolvedTheme==="living");assert.equal(await page.locator("html").getAttribute("data-resolved-theme"),"living","server default overrides public local");
await page.locator('label[for="pref-theme-light"]').click();await page.locator('label[for="pref-notebookWritingStyle-classic"]').click();await page.locator('label[for="pref-notebookPageStyle-lined"]').click();await page.getByRole("button",{name:"Tercihleri kaydet"}).click();await page.getByText("Görünüm tercihleriniz kaydedildi.").waitFor();await page.reload();await page.locator('.yd-shell-nav-item[data-shell-page="profile"]').click();assert.equal(await page.locator("html").getAttribute("data-resolved-theme"),"light");assert.equal(await page.locator("html").getAttribute("data-notebook-writing"),"classic");assert.equal(await page.locator("html").getAttribute("data-notebook-page"),"lined");
await page.locator('.yd-shell-nav-item[data-shell-page="research"]').click();await page.locator("#questionInput").fill("Mars");await page.locator("#searchButton").click();await page.locator("#results").waitFor({state:"visible"});
for(const theme of ["living","light","night","focus"]){await page.locator('.yd-shell-nav-item[data-shell-page="profile"]').click();await page.locator(`label[for="pref-theme-${theme}"]`).click();assert.equal(await page.locator("#commercialProfile").isVisible(),true);await page.locator('.yd-shell-nav-item[data-shell-page="research"]').click();assert.equal(await page.locator("#questionInput").isVisible(),true);await page.locator('.yd-shell-nav-item[data-shell-page="notebook"]').click();assert.equal(await page.locator("#notebookSection").isVisible(),true);const colors=await page.evaluate(()=>{const s=getComputedStyle(document.body);return[s.backgroundColor,s.color]});assert.notEqual(colors[0],colors[1],theme+" body contrast");}
await page.locator('.yd-shell-nav-item[data-shell-page="profile"]').click();await page.locator('label[for="pref-theme-light"]').click();await page.locator("#editProfileButton").click();assert.equal(await page.locator('.auth-card[role="dialog"]').isVisible(),true);await page.keyboard.press("Escape");
await page.getByRole("button",{name:/Çıkış yap/}).click();await page.locator("[data-open-login]").waitFor();assert.equal(await page.locator("html").getAttribute("data-resolved-theme"),"night","logout restores public local preference");await page.locator("[data-open-login]").click();await page.getByLabel("Kullanıcı adı veya e-posta").fill(name);await page.getByLabel("Parola",{exact:true}).fill(password);await page.getByRole("button",{name:"Giriş yap"}).click();await page.getByRole("button",{name:/Çıkış yap/}).waitFor();await page.locator('.yd-shell-nav-item[data-shell-page="profile"]').click();await page.waitForFunction(()=>document.documentElement.dataset.resolvedTheme==="light");
for(const width of [360,390,768,1024,1366]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=0,`overflow ${width}`);}
const radio=page.locator("#pref-theme-focus");await radio.focus();await page.keyboard.press("Space");assert.equal(await radio.isChecked(),true);assert.equal(await page.locator("#personalizationStatus").getAttribute("aria-live"),"polite");assert.deepEqual(consoleErrors,[]);assert.deepEqual(pageErrors,[]);assert.deepEqual(unexpected,[]);console.log("PASS  real Edge public local and authenticated personalization, live preview, accessibility, responsive matrix, and clean runtime");
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(child&&child.exitCode===null)child.kill("SIGTERM");await pool.query("DELETE FROM users WHERE username=$1",[name]).catch(()=>{});await pool.end();});
