"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),{spawn}=require("node:child_process"),{Pool}=require("pg");
if(!process.env.TEST_DATABASE_URL){console.log("SKIP  profile edit PostgreSQL E2E: TEST_DATABASE_URL is not set");process.exit(0);}
if(process.env.DATABASE_URL&&process.env.DATABASE_URL!==process.env.TEST_DATABASE_URL)throw new Error("TEST_DATABASE_URL_ONLY");
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,max:2}),suffix=crypto.randomBytes(5).toString("hex"),password="Profile-edit-password!";
const names={a:`profile_a_${suffix}`,b:`profile_b_${suffix}`,next:`profile_new_${suffix}`,oldEmail:`profile-a-${suffix}@example.test`,nextEmail:`profile-new-${suffix}@example.test`,bEmail:`profile-b-${suffix}@example.test`};let child;
async function wait(base){for(let i=0;i<60;i++){try{if((await fetch(base+"/api/status")).ok)return;}catch(_){}await new Promise(r=>setTimeout(r,100));}throw new Error("SERVER_NOT_READY");}
async function stop(){if(child&&child.exitCode===null){child.kill("SIGTERM");await new Promise(r=>child.once("exit",r));}}
async function call(base,path,method="GET",body,cookie){const response=await fetch(base+path,{method,headers:{Accept:"application/json",Origin:base,...(body?{"Content-Type":"application/json"}:{}),...(cookie?{Cookie:cookie}:{})},body:body&&JSON.stringify(body)});return{response,body:await response.json()};}
async function login(base,identifier){return call(base,"/api/auth/login","POST",{identifier,password});}
(async()=>{const port=36000+crypto.randomInt(10000),base=`http://127.0.0.1:${port}`;child=spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),AUTH_MODE:"production",ACCESS_MODE:"authenticated",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","inherit","inherit"]});await wait(base);
let a=await call(base,"/api/auth/register","POST",{username:names.a,email:names.oldEmail,password}),b=await call(base,"/api/auth/register","POST",{username:names.b,email:names.bEmail,password});assert.equal(a.response.status,201,JSON.stringify(a.body));assert.equal(b.response.status,201,JSON.stringify(b.body));const cookie=String(a.response.headers.get("set-cookie")).split(";")[0],id=a.body.user.id;
assert.equal((await call(base,"/api/auth/profile","PATCH",{username:names.next,email:names.nextEmail,displayName:"Profile A",currentPassword:"wrong password"},cookie)).response.status,401);
let updated=await call(base,"/api/auth/profile","PATCH",{username:names.next,email:names.nextEmail,displayName:"Profile A",currentPassword:password,userId:b.body.user.id,role:"TEACHER",studentId:"spoof",schoolId:"spoof"},cookie);assert.equal(updated.response.status,200);assert.equal(updated.body.user.id,id);assert.equal(updated.body.user.role,"USER");
let session=await call(base,"/api/auth/session","GET",null,cookie);assert.equal(session.body.user.username,names.next);assert.equal(session.body.user.email,names.nextEmail);
assert.equal((await login(base,names.next)).response.status,200);assert.equal((await login(base,names.nextEmail)).response.status,200);assert.equal((await login(base,names.a)).response.status,401);assert.equal((await login(base,names.oldEmail)).response.status,401);
assert.equal((await call(base,"/api/auth/profile","PATCH",{username:names.b,email:names.nextEmail,currentPassword:password},cookie)).response.status,409);assert.equal((await call(base,"/api/auth/profile","PATCH",{username:names.next,email:names.bEmail,currentPassword:password},cookie)).response.status,409);
await stop();child=spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),AUTH_MODE:"production",ACCESS_MODE:"authenticated",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","ignore","ignore"]});await wait(base);assert.equal((await login(base,names.next)).body.user.displayName,"Profile A");console.log("PASS  profile edit PostgreSQL identifiers, conflicts, session, persistence, restart, and mass assignment");
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await stop();await pool.query("DELETE FROM users WHERE username=ANY($1::text[])",[[names.a,names.b,names.next]]).catch(()=>{});await pool.end();});
