"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),{spawn}=require("node:child_process"),{Pool}=require("pg");
if(!process.env.TEST_DATABASE_URL){console.log("SKIP  smart notes PostgreSQL E2E: TEST_DATABASE_URL is not set");process.exit(0);}if(process.env.DATABASE_URL&&process.env.DATABASE_URL!==process.env.TEST_DATABASE_URL)throw new Error("TEST_DATABASE_URL_ONLY");
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,max:2}),suffix=crypto.randomBytes(5).toString("hex"),names={user:`sn_u_${suffix}`,studentA:`sn_sa_${suffix}`,studentB:`sn_sb_${suffix}`,teacher:`sn_t_${suffix}`},password="Smart-notes-test!",ids={};let child;
async function wait(base){for(let i=0;i<100;i++){try{if((await fetch(base+"/api/status")).ok)return;}catch(_){}await new Promise(r=>setTimeout(r,100));}throw Error("SERVER_TIMEOUT");}async function stop(){if(child&&child.exitCode===null){child.kill("SIGTERM");await new Promise(r=>child.once("exit",r));}}async function call(base,path,method="GET",body,cookie){const response=await fetch(base+path,{method,headers:{Accept:"application/json",Origin:base,...(body?{"Content-Type":"application/json"}:{}),...(cookie?{Cookie:cookie}:{})},body:body&&JSON.stringify(body)});return{response,body:await response.json().catch(()=>({}))};}
(async()=>{const port=41000+crypto.randomInt(3000),base=`http://127.0.0.1:${port}`,start=()=>spawn(process.execPath,["server.js"],{cwd:process.cwd(),env:{...process.env,PORT:String(port),ACCESS_MODE:"authenticated",AUTH_MODE:"production",STORAGE_MODE:"postgres",DATABASE_URL:process.env.TEST_DATABASE_URL,APP_ORIGIN:base,NODE_ENV:"test"},stdio:["ignore","ignore","ignore"]});child=start();await wait(base);const sessions={};for(const [key,name] of Object.entries(names)){const result=await call(base,"/api/auth/register","POST",{username:name,password});assert.equal(result.response.status,201,JSON.stringify(result.body));ids[key]=result.body.user.id;sessions[key]=String(result.response.headers.get("set-cookie")).split(";")[0];}
await pool.query("UPDATE users SET role='STUDENT' WHERE id=ANY($1::uuid[])",[[ids.studentA,ids.studentB]]);await pool.query("UPDATE users SET role='TEACHER' WHERE id=$1",[ids.teacher]);for(const key of ["studentA","studentB"]){const sid=crypto.randomUUID();ids[key+"Profile"]=sid;await pool.query("INSERT INTO students(id,user_id,display_name) VALUES($1,$2,$3)",[sid,ids[key],names[key]]);}
await call(base,"/api/auth/workspace","PUT",{selectedAreas:["work","research"],primaryArea:"work",onboardingCompleted:true},sessions.user);let research=await call(base,"/api/memory/save","POST",{topic:"Phase 2 Research",title:"Phase 2 Research",summary:"Immutable factual snapshot",keyFacts:["fact"]},sessions.user);assert.equal(research.response.status,200,JSON.stringify(research.body));assert.equal(research.body.memory.workspaceArea,"work");assert.equal(research.body.memory.contentType,"research");ids.research=research.body.memory.id;
const types=["note","meeting","project","idea","draft","journal","list","plan","reference"];for(const type of types){const created=await call(base,"/api/memory","POST",{title:`${type} title`,content:`${type} body`,workspaceArea:type==="idea"?"creative":"personal",contentType:type,tags:[type],metadata:type==="project"?{status:"active"}:type==="meeting"?{date:"2026-08-19"}:{}},sessions.user);assert.equal(created.response.status,201,`${type} ${JSON.stringify(created.body)}`);ids[type]=created.body.memory.id;}
let list=await call(base,"/api/memory/list?q=project&contentType=project", "GET",null,sessions.user);assert.equal(list.response.status,200);assert.equal(list.body.memories.length,1);let edit=await call(base,"/api/memory/"+ids.project,"PATCH",{customTitle:"Updated Project",content:"updated",workspaceArea:"work",contentType:"project",tags:["alpha","beta"],metadata:{status:"done"}},sessions.user);assert.equal(edit.response.status,200);assert.equal(edit.body.memory.noteMetadata.status,"done");edit=await call(base,"/api/memory/"+ids.research,"PATCH",{customTitle:"Custom Research",content:"tamper",workspaceArea:"research",contentType:"reference",tags:["safe"],metadata:{}},sessions.user);assert.equal(edit.body.memory.summary,"Immutable factual snapshot");
for(const [key,area,type] of [["studentA","creative","idea"],["studentA","personal","note"],["studentA","learning","reference"],["studentB","personal","journal"]]){const created=await call(base,"/api/memory","POST",{title:key+type,content:"student own",workspaceArea:area,contentType:type,tags:[],metadata:{}},sessions[key]);assert.equal(created.response.status,201);ids[key+type]=created.body.memory.id;}assert.equal((await call(base,"/api/memory/"+ids.studentBjournal,"PATCH",{customTitle:"steal",content:"x",workspaceArea:"personal",contentType:"note",tags:[],metadata:{}},sessions.studentA)).response.status,403);
const teacherNote=await call(base,"/api/memory","POST",{title:"Teacher own",content:"private",workspaceArea:"work",contentType:"note",tags:[],metadata:{}},sessions.teacher);assert.equal(teacherNote.response.status,201,JSON.stringify(teacherNote.body));assert.equal((await call(base,"/api/memory/"+ids.studentAnote,"PATCH",{customTitle:"teacher steal",content:"x",workspaceArea:"work",contentType:"note",tags:[],metadata:{}},sessions.teacher)).response.status,403);assert.equal((await call(base,"/api/memory","POST",{title:"spoof",content:"x",workspaceArea:"work",contentType:"note",tags:[],metadata:{},studentId:ids.studentAProfile},sessions.teacher)).response.status,403);
for(const bad of [{title:"x",content:"x",workspaceArea:"bad",contentType:"note",tags:[]},{title:"x",content:"x",workspaceArea:"work",contentType:"bad",tags:[]},{title:"x".repeat(121),content:"x",workspaceArea:"work",contentType:"note",tags:[]},{title:"x",content:"x",workspaceArea:"work",contentType:"note",tags:Array(9).fill("x")}])assert.equal((await call(base,"/api/memory","POST",bad,sessions.user)).response.status,400);assert.equal((await call(base,"/api/memory","POST",{title:"public",content:"x",workspaceArea:"work",contentType:"note",tags:[]})).response.status,401);
await stop();child=start();await wait(base);list=await call(base,"/api/memory/list","GET",null,sessions.user);assert.ok(list.body.memories.some(x=>x.title==="Updated Project"));assert.equal((await call(base,"/api/memory/"+ids.idea,"DELETE",null,sessions.user)).response.status,200);console.log("PASS  smart notes PostgreSQL USER all types, research compatibility, filters, edit/delete, restart, STUDENT isolation and TEACHER own-note authority");
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;}).finally(async()=>{await stop();try{await pool.query("DELETE FROM users WHERE username=ANY($1::text[])",[Object.values(names)]);}finally{await pool.end();}});
