"use strict";
const assert=require("node:assert/strict"),visual=require("../brain/visualIntelligence");
const intentMatrix={"Mars":"SCIENTIFIC_OBJECT","Mars fotoğrafları":"PHOTO_REQUEST","Mars yüzeyi":"SCIENTIFIC_OBJECT","Mars ile Dünya karşılaştırması":"COMPARISON","Atatürk fotoğrafları":"HISTORICAL_PERSON","Kara delik nasıl oluşur?":"SCIENTIFIC_OBJECT","DNA yapısı":"DIAGRAM_REQUEST","İnsan kalbi anatomisi":"ANATOMY","Bugünkü uzay gelişmeleri":"CURRENT_EVENT","Kara delik diyagramı":"DIAGRAM_REQUEST","Kalbin bölümleri":"ANATOMY"};for(const [query,intent] of Object.entries(intentMatrix))assert.equal(visual.classifyVisualIntent(query,{topic:query}),intent,query);
const standardReport=[];for(const query of ["Atatürk","Mars","Kara delik","DNA","İnsan kalbi","Güneş Sistemi","Roma İmparatorluğu","Toryum"]){const context=visual.createContext(query,{topic:query,originalQuestion:query});assert.ok(context.queries.length>=1&&context.queries.length<=4,query);const slug=visual.fold(query).replace(/ /g,"-");const good={title:`${context.entity} portrait scientific photograph diagram`,description:`${context.entity} educational image`,image:`https://upload.wikimedia.org/wikipedia/commons/${slug}.jpg`,url:`https://upload.wikimedia.org/wikipedia/commons/${slug}.jpg`,original:`https://upload.wikimedia.org/wikipedia/commons/${slug}.jpg`,sourceUrl:`https://commons.wikimedia.org/wiki/File:${slug}.jpg`,mime:"image/jpeg",width:1400,height:900,license:"CC BY-SA 4.0",queryUsed:context.queries[0].query};const results=visual.rankCandidates([good,{...good,image:`https://upload.wikimedia.org/wikipedia/commons/thumb/${slug}.jpg/800px-${slug}.jpg`,url:`https://upload.wikimedia.org/wikipedia/commons/thumb/${slug}.jpg/800px-${slug}.jpg`},{...good,title:`${query} logo icon`,image:`https://upload.wikimedia.org/wikipedia/commons/${slug}-logo.png`,url:`https://upload.wikimedia.org/wikipedia/commons/${slug}-logo.png`,original:`https://upload.wikimedia.org/wikipedia/commons/${slug}-logo.png`,sourceUrl:`https://commons.wikimedia.org/wiki/File:${slug}-logo.png`}],context);assert.equal(results.length,1,query);standardReport.push({query,imageCount:results.length,topRelevance:results[0].relevanceScore,logoCount:results.filter(x=>["LOGO","ICON"].includes(x.visualType)).length,duplicateCount:0});}
assert.deepEqual(visual.expandImageQueries("Bugünkü teknoloji",{topic:"teknoloji"}),[]);assert.deepEqual(visual.comparisonEntities("Mars vs Dünya"),["Mars","Dünya"]);assert.equal(visual.expandImageQueries("Mars vs Dünya",{topic:"Mars vs Dünya"})[0].side,"left");
assert.equal(visual.resolveEntity("Apple teknoloji",{topic:"Apple"}),"Apple Inc.");assert.equal(visual.resolveEntity("Apple meyve",{topic:"Apple"}),"apple fruit");assert.equal(visual.resolveEntity("Java programlama",{topic:"Java"}),"Java programming language");assert.equal(visual.resolveEntity("Mercury gezegen",{topic:"Mercury"}),"Mercury planet");assert.equal(visual.resolveEntity("Nikola Tesla bilim insanı",{topic:"Tesla"}),"Nikola Tesla portrait");
for(const ambiguous of ["Java","Apple","Mercury","Tesla"])assert.deepEqual(visual.expandImageQueries(ambiguous,{topic:ambiguous}),[],`${ambiguous} unresolved visual safety`);
const context=visual.createContext("Atatürk fotoğrafları",{topic:"Mustafa Kemal Atatürk"});const fixture=[
 {title:"Mustafa Kemal Atatürk portrait photograph",description:"Atatürk portrait",image:"https://upload.wikimedia.org/wikipedia/commons/a/a1/Ataturk.jpg",url:"https://upload.wikimedia.org/wikipedia/commons/a/a1/Ataturk.jpg",original:"https://upload.wikimedia.org/wikipedia/commons/a/a1/Ataturk.jpg",sourceUrl:"https://commons.wikimedia.org/wiki/File:Ataturk.jpg",mime:"image/jpeg",width:1200,height:1600,license:"Public domain",attribution:"Wikimedia Commons"},
 {title:"800px-Mustafa Kemal Atatürk portrait photograph",description:"Atatürk portrait duplicate",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Ataturk.jpg/800px-Ataturk.jpg",url:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Ataturk.jpg/800px-Ataturk.jpg",original:"https://upload.wikimedia.org/wikipedia/commons/a/a1/Ataturk.jpg",sourceUrl:"https://commons.wikimedia.org/wiki/File:Ataturk.jpg",mime:"image/jpeg",width:800,height:1000,license:"Public domain"},
 {title:"Atatürk logo icon",description:"brand logo",image:"https://upload.wikimedia.org/wikipedia/commons/a/logo.png",url:"https://upload.wikimedia.org/wikipedia/commons/a/logo.png",sourceUrl:"https://commons.wikimedia.org/wiki/File:logo.png",mime:"image/png",width:1000,height:1000},
 {title:"Random building",description:"unrelated building",image:"https://upload.wikimedia.org/wikipedia/commons/b/building.jpg",url:"https://upload.wikimedia.org/wikipedia/commons/b/building.jpg",sourceUrl:"https://commons.wikimedia.org/wiki/File:building.jpg",mime:"image/jpeg",width:1200,height:800}
];const ranked=visual.rankCandidates(fixture,context);assert.equal(ranked.length,1);assert.equal(ranked[0].visualType,"PORTRAIT");assert.equal(ranked[0].isHero,true);assert.equal(ranked[0].license,"Public domain");assert.ok(ranked[0].relevanceScore>=70);
const unknown=visual.rankCandidates([{title:"Mars planet photo",description:"Mars",image:"https://upload.wikimedia.org/wikipedia/commons/m/mars.jpg",url:"https://upload.wikimedia.org/wikipedia/commons/m/mars.jpg",sourceUrl:"https://commons.wikimedia.org/wiki/File:Mars.jpg",mime:"image/jpeg",width:900,height:900}],visual.createContext("Mars",{topic:"Mars"}));assert.equal(unknown[0].license,"Belirtilmemiş");assert.doesNotMatch(unknown[0].license,/free to use|serbest kullanım/i);
console.log("PASS  visual intent, controlled expansion, ambiguous identity, comparison sides, relevance gate, logo and duplicate filtering, hero and license safety matrices",JSON.stringify(standardReport));
