"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const js = fs.readFileSync(path.join(root, "assets/js/workspace-shell.js"), "utf8");
const css = fs.readFileSync(path.join(root, "assets/css/workspace-shell-15-6.css"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
for (const page of ["home", "research", "notebook", "collections", "personal", "profile"]) assert.match(js, new RegExp('"' + page + '"'));
assert.match(js, /role: "tablist"/);
assert.match(js, /aria-selected/);
assert.match(js, /ArrowLeft\|ArrowRight\|Home\|End/);
assert.match(js, /pointerType === "touch"/);
assert.match(js, /closest\("input,textarea,select,button,a,\[contenteditable\]"\)/);
assert.match(js, /slice\(0\)|pages\.slice/);
assert.match(js, /authenticated !== true/);
assert.match(js, /role === "TEACHER"/);
assert.match(js, /legacyObserver\.observe/);
assert.match(js, /output\.textContent !== value/);
assert.match(js, /data-auth-user/);
assert.match(css, /prefers-reduced-motion:reduce/);
assert.match(css, /@media\(max-width:767px\)/);
assert.match(css, /overflow-x:hidden/);
assert.match(css, /grid-template-columns:repeat\(5/);
assert.match(html, /assets\/css\/workspace-shell-15-6\.css/);
assert.match(html, /assets\/js\/workspace-shell\.js/);
console.log("PASS  15.6 authenticated shell structure, navigation, touch guard, reduced motion and responsive CSS");
