"use strict";

const db = require("../db");
const { mapDatabaseError, jsonValue, page } = require("./errors");

function mapMemory(row) { if (!row) return null; const iso = value => value instanceof Date ? value.toISOString() : value || null; return { id: row.id, studentId: row.student_id, ownerUserId: row.owner_user_id || null, topic: row.topic, normalizedTopic: row.normalized_topic, title: row.custom_title || row.title, originalTitle: row.title, summary: row.summary || "", workspaceArea: row.workspace_area || "research", contentType: row.content_type || "research", customTitle: row.custom_title || "", tags: row.tags || [], noteMetadata: row.note_metadata || {}, confidence: Number(row.confidence || 0), sourceCount: Number(row.source_count || 0), audienceLevel: row.audience_level || "general", timesSearched: Number(row.times_searched || 1), keyConcepts: row.key_concepts || [], keyFacts: row.key_facts || [], relatedTopics: row.related_topics || [], reliabilitySummary: row.reliability_summary || {}, quizSummary: row.quiz_summary || {}, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function owner(value) { return value && typeof value === "object" && value.kind === "user" ? { column: "owner_user_id", id: value.id, studentId: null, userId: value.id } : { column: "student_id", id: value, studentId: value, userId: null }; }
async function findByStudent(studentId, options = {}, client = db) { const limit = page(options.limit, 50, 100); const offset = Math.max(0, Number.parseInt(options.offset, 10) || 0); const scope = owner(studentId); const values = [scope.id]; const filters = []; if (options.workspaceArea) { values.push(options.workspaceArea); filters.push(`workspace_area = $${values.length}`); } if (options.contentType) { values.push(options.contentType); filters.push(`content_type = $${values.length}`); } if (options.search) { values.push(`%${String(options.search).toLocaleLowerCase("tr-TR")}%`); filters.push(`(LOWER(COALESCE(custom_title,title)) LIKE $${values.length} OR LOWER(topic) LIKE $${values.length} OR EXISTS (SELECT 1 FROM unnest(tags) tag WHERE LOWER(tag) LIKE $${values.length}))`); } values.push(limit, offset); try { const result = await client.query(`SELECT * FROM memory_records WHERE ${scope.column} = $1 ${filters.length ? `AND ${filters.join(" AND ")}` : ""} ORDER BY updated_at DESC, id LIMIT $${values.length - 1} OFFSET $${values.length}`, values); return result.rows.map(mapMemory); } catch (error) { throw mapDatabaseError(error, "MEMORY_LIST_FAILED"); } }
async function findByStudentAndTopic(studentId, normalizedTopic, client = db) { const scope = owner(studentId); const result = await client.query(`SELECT * FROM memory_records WHERE ${scope.column} = $1 AND normalized_topic = $2 LIMIT 1`, [scope.id, normalizedTopic]); return mapMemory(result.rows[0]); }
async function upsertTopic(input, client = db) { const value = input && typeof input === "object" ? input : {}; const scope = owner(value.studentId); const fields = [value.id, scope.studentId, scope.userId, value.topic, value.normalizedTopic, value.title || value.topic, value.summary || "", Number(value.confidence || 0), Number(value.sourceCount || 0), value.audienceLevel || "general", Number(value.timesSearched || 1), jsonValue(value.keyConcepts, "[]"), jsonValue(value.keyFacts, "[]"), jsonValue(value.relatedTopics, "[]"), jsonValue(value.reliabilitySummary, "{}"), jsonValue(value.quizSummary, "{}"), value.workspaceArea || "research", value.contentType || "research", value.customTitle || null, value.tags || [], jsonValue(value.noteMetadata, "{}")]; const conflict = scope.userId ? "(owner_user_id, normalized_topic) WHERE owner_user_id IS NOT NULL" : "(student_id, normalized_topic)"; try { const result = await client.query(`INSERT INTO memory_records (id, student_id, owner_user_id, topic, normalized_topic, title, summary, confidence, source_count, audience_level, times_searched, key_concepts, key_facts, related_topics, reliability_summary, quiz_summary, workspace_area, content_type, custom_title, tags, note_metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb,$16::jsonb,$17,$18,$19,$20::text[],$21::jsonb) ON CONFLICT ${conflict} DO UPDATE SET topic=EXCLUDED.topic,title=EXCLUDED.title,summary=EXCLUDED.summary,confidence=EXCLUDED.confidence,source_count=EXCLUDED.source_count,audience_level=EXCLUDED.audience_level,times_searched=EXCLUDED.times_searched,key_concepts=EXCLUDED.key_concepts,key_facts=EXCLUDED.key_facts,related_topics=EXCLUDED.related_topics,reliability_summary=EXCLUDED.reliability_summary,quiz_summary=EXCLUDED.quiz_summary,workspace_area=EXCLUDED.workspace_area,content_type=EXCLUDED.content_type,custom_title=EXCLUDED.custom_title,tags=EXCLUDED.tags,note_metadata=EXCLUDED.note_metadata,updated_at=NOW() RETURNING *`, fields); return mapMemory(result.rows[0]); } catch (error) { throw mapDatabaseError(error, "MEMORY_UPSERT_FAILED"); } }
async function createNote(input, client = db) { return upsertTopic({ ...input, normalizedTopic: `note:${input.id}`, confidence: 0, sourceCount: 0, timesSearched: 1 }, client); }
async function updateOwned(id, studentId, value, client = db) { const scope = owner(studentId); try { const result = await client.query(`WITH target AS (SELECT id FROM memory_records WHERE id=$1), updated AS (UPDATE memory_records SET custom_title=$3,workspace_area=$4,content_type=$5,tags=$6::text[],summary=CASE WHEN content_type='research' THEN summary ELSE $7 END,note_metadata=CASE WHEN content_type='research' THEN note_metadata ELSE $8::jsonb END,updated_at=NOW() WHERE id=$1 AND ${scope.column}=$2 RETURNING *) SELECT EXISTS(SELECT 1 FROM target) exists,(SELECT row_to_json(updated) FROM updated LIMIT 1) record`, [id, scope.id, value.customTitle || null, value.workspaceArea, value.contentType, value.tags, value.content || "", jsonValue(value.noteMetadata, "{}")]); const row=result.rows[0]||{}; return { exists:Boolean(row.exists), memory:mapMemory(row.record) }; } catch(error){ throw mapDatabaseError(error,"MEMORY_UPDATE_FAILED"); } }
async function listRecent(studentId, options = {}, client = db) { return findByStudent(studentId, options, client); }
async function countByStudent(studentId, client = db) { const scope = owner(studentId); const result = await client.query(`SELECT COUNT(*)::int AS count FROM memory_records WHERE ${scope.column} = $1`, [scope.id]); return Number(result.rows[0]?.count || 0); }
async function getProgressSource(studentId, options = {}, client = db) { return findByStudent(studentId, options, client); }
async function deleteOwned(id, studentId, client = db) { const scope = owner(studentId); try { const result = await client.query(`WITH target AS (SELECT id FROM memory_records WHERE id = $1), deleted AS (DELETE FROM memory_records WHERE id = $1 AND ${scope.column} = $2 RETURNING id) SELECT EXISTS (SELECT 1 FROM target) AS exists, EXISTS (SELECT 1 FROM deleted) AS deleted`, [id, scope.id]); const row = result.rows[0] || {}; return { exists: Boolean(row.exists), deleted: Boolean(row.deleted) }; } catch (error) { throw mapDatabaseError(error, "MEMORY_DELETE_FAILED"); } }

module.exports = { name: "memory", mapMemory, findByStudent, findByStudentAndTopic, upsertTopic, createNote, updateOwned, listRecent, countByStudent, getProgressSource, deleteOwned };
