"use strict";

const db = require("../db");
const { mapDatabaseError, jsonValue, page } = require("./errors");

function mapMemory(row) { if (!row) return null; const iso = value => value instanceof Date ? value.toISOString() : value || null; return { id: row.id, studentId: row.student_id, topic: row.topic, normalizedTopic: row.normalized_topic, title: row.title, summary: row.summary || "", confidence: Number(row.confidence || 0), sourceCount: Number(row.source_count || 0), audienceLevel: row.audience_level || "general", timesSearched: Number(row.times_searched || 1), keyConcepts: row.key_concepts || [], keyFacts: row.key_facts || [], relatedTopics: row.related_topics || [], reliabilitySummary: row.reliability_summary || {}, quizSummary: row.quiz_summary || {}, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
async function findByStudent(studentId, options = {}, client = db) { const limit = page(options.limit); const offset = Math.max(0, Number.parseInt(options.offset, 10) || 0); try { const result = await client.query("SELECT * FROM memory_records WHERE student_id = $1 ORDER BY updated_at DESC, id LIMIT $2 OFFSET $3", [studentId, limit, offset]); return result.rows.map(mapMemory); } catch (error) { throw mapDatabaseError(error, "MEMORY_LIST_FAILED"); } }
async function findByStudentAndTopic(studentId, normalizedTopic, client = db) { const result = await client.query("SELECT * FROM memory_records WHERE student_id = $1 AND normalized_topic = $2 LIMIT 1", [studentId, normalizedTopic]); return mapMemory(result.rows[0]); }
async function upsertTopic(input, client = db) { const value = input && typeof input === "object" ? input : {}; const id = value.id; const fields = [id, value.studentId, value.topic, value.normalizedTopic, value.title || value.topic, value.summary || "", Number(value.confidence || 0), Number(value.sourceCount || 0), value.audienceLevel || "general", Number(value.timesSearched || 1), jsonValue(value.keyConcepts, "[]"), jsonValue(value.keyFacts, "[]"), jsonValue(value.relatedTopics, "[]"), jsonValue(value.reliabilitySummary, "{}"), jsonValue(value.quizSummary, "{}")]; try { const result = await client.query(`INSERT INTO memory_records (id, student_id, topic, normalized_topic, title, summary, confidence, source_count, audience_level, times_searched, key_concepts, key_facts, related_topics, reliability_summary, quiz_summary) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb) ON CONFLICT (student_id, normalized_topic) DO UPDATE SET topic=EXCLUDED.topic,title=EXCLUDED.title,summary=EXCLUDED.summary,confidence=EXCLUDED.confidence,source_count=EXCLUDED.source_count,audience_level=EXCLUDED.audience_level,times_searched=EXCLUDED.times_searched,key_concepts=EXCLUDED.key_concepts,key_facts=EXCLUDED.key_facts,related_topics=EXCLUDED.related_topics,reliability_summary=EXCLUDED.reliability_summary,quiz_summary=EXCLUDED.quiz_summary,updated_at=NOW() RETURNING *`, fields); return mapMemory(result.rows[0]); } catch (error) { throw mapDatabaseError(error, "MEMORY_UPSERT_FAILED"); } }
async function listRecent(studentId, options = {}, client = db) { return findByStudent(studentId, options, client); }
async function countByStudent(studentId, client = db) { const result = await client.query("SELECT COUNT(*)::int AS count FROM memory_records WHERE student_id = $1", [studentId]); return Number(result.rows[0]?.count || 0); }
async function getProgressSource(studentId, options = {}, client = db) { return findByStudent(studentId, options, client); }

module.exports = { name: "memory", mapMemory, findByStudent, findByStudentAndTopic, upsertTopic, listRecent, countByStudent, getProgressSource };
